import { type TriggerContext, type JSONObject } from "@devvit/public-api";
import { Datetime_global } from 'datetime_global/Datetime_global.ts';
export const oneDayInseconds = 86400;
export const Expire = oneDayInseconds * 90;

export async function scheduleJob(context: TriggerContext, name: string, hourTime: number, minutes: number, data: JSONObject = {}) {
  const jobName = 'jobId-' + name, oldJobId = await context.redis.get(jobName);
  if (oldJobId) {
    await context.redis.del(jobName);
    await context.scheduler.cancelJob(oldJobId);
  }
  const jobId = await context.scheduler.runJob({
    cron: `${minutes} ${hourTime} * * *`,
    name, data,
  });
  await context.redis.set(jobName, jobId);
  return jobId;
}

export function waterMark(subredditName?: string) {
  if (subredditName === undefined)
    return '[Generated By Moderator Statistics](https://developers.reddit.com/apps/modlogstats)';
  return `[View The Modlog Summery Here](https://old.reddit.com/r/${subredditName}/wiki/modlog-stats/)`
    + ` [and The Modmail Summery Here](https://old.reddit.com/r/${subredditName}/wiki/modmail-stats/)`
    + '  \n[Generated By Moderator Statistics](https://developers.reddit.com/apps/modlogstats)';
}

export function formatTimeURL(datetime: Datetime_global | Date): string {
  const escapeParenteses = (string: string): string => string.replaceAll(/[\[\]]/g, (strx: string) => `\\${strx}`);
  if (datetime instanceof Datetime_global) {
    return `[${escapeParenteses(datetime.toString())}](https://clock.ant.ractoc.com/?t=${datetime.toISOString()})`;
  } {// @ts-expect-error
    const date = new Date(datetime);
    return `[${escapeParenteses(date.toString())}](https://clock.ant.ractoc.com/?t=${date.toISOString()})`;
  }
}
